version: 2

builds:
  # xcrush - the build tool for creating custom Crush distributions
  - id: xcrush
    dir: ./crush-plugin-poc
    main: ./cmd/xcrush
    binary: xcrush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  # crush-extended - Crush with community plugins
  - id: crush-extended
    main: ./cmd/crush-extended
    binary: crush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: xcrush-archive
    builds:
      - xcrush
    name_template: >-
      xcrush_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - LICENSE*
      - README*

  - id: crush-extended-archive
    builds:
      - crush-extended
    name_template: >-
      crush-extended_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - LICENSE*
      - README*

nfpms:
  # xcrush packages
  - id: xcrush-pkg
    builds:
      - xcrush
    package_name: xcrush
    file_name_template: >-
      xcrush_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    vendor: "Unofficial Crush Build Tool"
    homepage: https://github.com/aleksclark/crush-modules
    maintainer: Aleks Clark <aleks.clark@gmail.com>
    description: |
      ⚠️  UNOFFICIAL TOOL ⚠️
      
      Build tool for creating custom Crush distributions with plugins.
      
      This is NOT an official Charm Labs tool. Use at your own risk.
      
      xcrush allows you to build custom Crush binaries with selected plugins.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

  # crush-extended packages
  - id: crush-extended-pkg
    builds:
      - crush-extended
    package_name: crush-extended
    file_name_template: >-
      crush-extended_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    vendor: "Unofficial Crush Build"
    homepage: https://github.com/aleksclark/crush-modules
    maintainer: Aleks Clark <aleks.clark@gmail.com>
    description: |
      ⚠️  UNOFFICIAL BUILD ⚠️
      
      Crush with community plugins: otlp, agent-status, periodic-prompts.
      
      This is NOT an official Charm Labs release. Use at your own risk.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    conflicts:
      - crush

brews:
  # xcrush Homebrew formula
  - ids:
      - xcrush-archive
    name: xcrush
    repository:
      owner: aleksclark
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore(brew): update {{ .ProjectName }} to {{ .Tag }}"
    directory: Formula
    homepage: https://github.com/aleksclark/crush-modules
    description: "Unofficial build tool for creating custom Crush distributions with plugins"
    license: MIT
    install: |
      bin.install "xcrush"
    test: |
      system "#{bin}/xcrush", "--version"

  # crush-extended Homebrew formula
  - ids:
      - crush-extended-archive
    name: crush-extended
    repository:
      owner: aleksclark
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore(brew): update crush-extended to {{ .Tag }}"
    directory: Formula
    homepage: https://github.com/aleksclark/crush-modules
    description: "Unofficial Crush build with community plugins (otlp, agent-status, periodic-prompts)"
    license: MIT
    conflicts:
      - crush
    install: |
      bin.install "crush"
    test: |
      system "#{bin}/crush", "--version"
    caveats: |
      WARNING: This is an UNOFFICIAL build of Crush with experimental plugins.
      This is NOT supported by Charm Labs. Use at your own risk.

aurs:
  # xcrush AUR package
  - name: xcrush-bin
    ids:
      - xcrush-archive
    homepage: https://github.com/aleksclark/crush-modules
    description: "Unofficial build tool for creating custom Crush distributions with plugins"
    maintainers:
      - 'Aleks Clark <aleks dot clark at gmail dot com>'
    contributors:
      - 'Aleks Clark <aleks dot clark at gmail dot com>'
    license: MIT
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/xcrush-bin.git'
    commit_author:
      name: Aleks Clark
      email: aleks.clark@gmail.com
    commit_msg_template: "chore: update to {{ .Tag }}"
    package: |-
      # bin
      install -Dm755 "./xcrush" "${pkgdir}/usr/bin/xcrush"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/xcrush/LICENSE"
    provides:
      - xcrush

  # crush-extended AUR package
  - name: crush-extended-bin
    ids:
      - crush-extended-archive
    homepage: https://github.com/aleksclark/crush-modules
    description: "Unofficial Crush build with community plugins (otlp, agent-status, periodic-prompts)"
    maintainers:
      - 'Aleks Clark <aleks dot clark at gmail dot com>'
    contributors:
      - 'Aleks Clark <aleks dot clark at gmail dot com>'
    license: MIT
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/crush-extended-bin.git'
    commit_author:
      name: Aleks Clark
      email: aleks.clark@gmail.com
    commit_msg_template: "chore: update to {{ .Tag }}"
    conflicts:
      - crush
    package: |-
      # bin
      install -Dm755 "./crush" "${pkgdir}/usr/bin/crush"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/crush-extended/LICENSE"
    provides:
      - crush

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: aleksclark
    name: crush-modules
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## ⚠️  UNOFFICIAL BUILDS - USE AT YOUR OWN RISK
    
    These are **NOT** official Charm Labs releases. These builds include experimental
    community plugins that have not been reviewed or tested by Charm Labs.
    
    ### What's included:
    
    - **crush-extended**: Crush with otlp, agent-status, and periodic-prompts plugins
    - **xcrush**: Build tool for creating custom Crush distributions
    
    For the official Crush release, visit: https://github.com/charmbracelet/crush
