version: 2

before:
  hooks:
    - ./scripts/prebuild.sh

builds:
  # xcrush - the build tool for creating custom Crush distributions
  - id: xcrush
    dir: ./crush-plugin-poc
    main: ./cmd/xcrush
    binary: xcrush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: xcrush-archive
    builds:
      - xcrush
    name_template: >-
      xcrush_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - LICENSE*
      - README*

  # crush-extended - single archive with all prebuilt binaries
  # Using meta flag to avoid goos/goarch expansion
  - id: crush-extended-linux-amd64
    format: tar.gz
    name_template: "crush-extended_{{ .Version }}_linux_x86_64"
    meta: true
    files:
      - src: build/crush-extended_linux_amd64
        dst: crush-extended
      - LICENSE*
      - README*

  - id: crush-extended-linux-arm64
    format: tar.gz
    name_template: "crush-extended_{{ .Version }}_linux_arm64"
    meta: true
    files:
      - src: build/crush-extended_linux_arm64
        dst: crush-extended
      - LICENSE*
      - README*

  - id: crush-extended-darwin-amd64
    format: tar.gz
    name_template: "crush-extended_{{ .Version }}_darwin_x86_64"
    meta: true
    files:
      - src: build/crush-extended_darwin_amd64
        dst: crush-extended
      - LICENSE*
      - README*

  - id: crush-extended-darwin-arm64
    format: tar.gz
    name_template: "crush-extended_{{ .Version }}_darwin_arm64"
    meta: true
    files:
      - src: build/crush-extended_darwin_arm64
        dst: crush-extended
      - LICENSE*
      - README*

nfpms:
  # NOTE: crush-extended nfpms disabled temporarily due to meta/builds:[] platform expansion issues
  # TODO: Re-enable once we figure out how to prevent duplicate artifacts
  
  # xcrush packages
  - id: xcrush-pkg
    builds:
      - xcrush
    package_name: xcrush
    file_name_template: >-
      xcrush_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    vendor: "Unofficial Crush Build Tool"
    homepage: https://github.com/aleksclark/crush-modules
    maintainer: Aleks Clark <aleks.clark@gmail.com>
    description: |
      ⚠️  UNOFFICIAL TOOL ⚠️
      
      Build tool for creating custom Crush distributions with plugins.
      
      This is NOT an official Charm Labs tool. Use at your own risk.
      
      xcrush allows you to build custom Crush binaries with selected plugins.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

brews:
  # NOTE: All brews disabled temporarily - HOMEBREW_TAP_GITHUB_TOKEN needs better permissions
  # TODO: Re-enable once token is fixed
  []

aurs:
  # NOTE: crush-extended AUR package disabled for now due to meta archive compatibility issues
  # TODO: Re-enable once we figure out how to handle prebuilt binaries with AUR
  
  # xcrush AUR package
  - name: xcrush-bin
    homepage: https://github.com/aleksclark/crush-modules
    description: "Unofficial build tool for creating custom Crush distributions with plugins"
    maintainers:
      - 'Aleks Clark <aleks dot clark at gmail dot com>'
    contributors:
      - 'Aleks Clark <aleks dot clark at gmail dot com>'
    license: MIT
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/xcrush-bin.git'
    commit_author:
      name: Aleks Clark
      email: aleks.clark@gmail.com
    commit_msg_template: "chore: update to {{ .Tag }}"
    package: |-
      # bin
      install -Dm755 "./xcrush" "${pkgdir}/usr/bin/xcrush"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/xcrush/LICENSE"
    provides:
      - xcrush
    ids:
      - xcrush-archive

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: aleksclark
    name: crush-modules
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## ⚠️  UNOFFICIAL BUILDS - USE AT YOUR OWN RISK
    
    These are **NOT** official Charm Labs releases. These builds include experimental
    community plugins that have not been reviewed or tested by Charm Labs.
    
    ### What's included:
    
    - **crush-extended**: Crush with otlp, agent-status, and periodic-prompts plugins
    - **xcrush**: Build tool for creating custom Crush distributions
    
    For the official Crush release, visit: https://github.com/charmbracelet/crush
